spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_contracts
    username: app_user
    password: password
    driverClassName: org.postgresql.Driver
grpc:
  port: 50052
server:
  port: 8082
  http2:
    enabled: true
  ssl:
    enabled: false
