spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_customers
    username: app_user
    password: password
    driverClassName: org.postgresql.Driver
grpc:
  port: 50051
server:
  port: 8081
  http2:
    enabled: true
  ssl:
    enabled: false
