spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: password
    driverClassName: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password: null
    database: 0
