spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_permissions
    username: app_user
    password: password
    driverClassName: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password: null
    database: 0
server:
  port: 50053
  http2:
    enabled: true
  ssl:
    enabled: false
